version: '3.8'

services:
  ollama:
    build: ./ollama
    image: ollama/ollama:latest
    ports:
        - 11434:11434
    volumes:
        - ./ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    restart: always

  backend:
    depends_on:
      - ollama
    build: ./backend
    ports:
      - "4001:4001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=4001

  frontend:
    depends_on:
      - backend
    build: ./frontend
    ports:
      - "4000:4000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_PORT=4000
