version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "4001:4001"
    environment:
      - NODE_ENV=development
      - PORT=4001

  frontend:
    build: ./frontend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - VITE_PORT=4000
    depends_on:
      - backend
